version: "3.7"

services:
  purrfect-creations-seerve:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/purrfect-creations/server/src
      - ./nodemon.json:/purrfect-creations/server/nodemon.json
    container_name: purrfect-creations-server
    expose:
      - "4000"
    ports:
      - "4000:4000"
    command: npm run dev
